.PHONY: all clean run run-log debug profile

.ONESHELL:

VERSION ?= 0.1.0
NAME ?= halen
BUILD_DIR ?= build

CC ?= gcc
CFLAGS += -Wall -Wextra -std=gnu99 -O0 -I$(BUILD_DIR) -I$(SRC_DIR) $(shell pkg-config --cflags x11 xtst xext xfixes fontconfig xft)
LIBS = $(shell pkg-config --libs x11 xtst xext xfixes fontconfig xft) -lpthread
SRC_DIR = src

ifdef DEBUG
CFLAGS += -fsanitize=address -fno-omit-frame-pointer -g
LDFLAGS += -fsanitize=address
endif

ifdef PROFILE
CFLAGS += -g -O1
endif

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ = $(SRC:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
EXEC = $(BUILD_DIR)/$(NAME)

LOG = .gcc

all: $(EXEC) 

$(EXEC): $(OBJ)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

$(BUILD_DIR)/%.o: src/%.c $(BUILD_DIR)/config.h | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

run:
	rm -f .log $(LOG) 
	$(MAKE) clean
	$(MAKE) $(EXEC) --no-print-directory 2>&1 | tee -a $(LOG)
	./$(EXEC) -c .config -V

run-log:
	# signals doesnt work perfect when we PIPE to tee..
	rm -f .log $(LOG) 
	$(MAKE) clean
	$(MAKE) $(EXEC) --no-print-directory 2>&1 | tee -a $(LOG)
	./$(EXEC) -c .config -V | tee -a .log

clean:
	rm -rf $(BUILD_DIR) $(LOG)

$(BUILD_DIR)/config.h: makefile | $(BUILD_DIR)
	@echo "/* Generated by makefile */" > $@
	@echo "#define VERSION \"$(VERSION)\"" >> $@
	@echo "#define PROGRAM_NAME \"$(NAME)\"" >> $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)	

debug:
	$(MAKE) clean
	$(MAKE) DEBUG=1 $(EXEC)
	./$(EXEC) -c .config -V

profile:
	$(MAKE) clean
	$(MAKE) PROFILE=1 $(EXEC)
	heaptrack ./$(EXEC) -c .config -V
